pages/checkout/index.tsx
src/components/LineItem.tsx
src/components/LineItemImage.tsx

- fix: Regroup bundle items
- feat: Add new prop placeholder and set placeholder image if src is empty

fix: Regroup bundle items and set placeholder image to LineItemImage

---

src/components/CheckoutLink.tsx
src/components/CustomerInput.tsx

- fix: Expose customer email through onBlur function
- feat: CheckoutLink is linked to hosted checkout by default with a boolean prop `hostedCheckout`

feat: Add new boolean prop `hostedCheckout` to `CheckoutLink`

---

src/components/OrderContainer.tsx
src/components/Shipment.tsx
src/components/ShipmentsContainer.tsx
src/components/ShippingMethodRadioButton.tsx

- fix: Reset shipping method selector when add or remove a coupon
- perf: `autoSelectSingleShippingMethod` accept even a function

fix: Reset shipping method selector

---

packages/react-components/src/components/payment_methods/PaymentMethodName.tsx

Add payment method reference to `PaymentMethodName` so it would be easier to distinguish different payment methods with the same source type.
Scenario example:
A commerce has 2 wire_transfers methods one for cash flow one for wire_transfer, right now it won't be able to distinguish them. 
```
<PaymentMethodName>
{({ labelName, htmlFor, paymentReference, ...props }) => {
console.log(paymentReference)
return (
<label htmlFor={htmlFor}>{label}</label>
)
}}
</PaymentMethodName>
```

Add payment_gateway in the PaymentMethodName children fn props

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/OrderList.tsx

Closes #435
I've fixed the condition used to check if empty content needs to be rendered.

Prevent empty list of orders or subscriptions to break the rendering

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/OrderList.tsx

I restored the usage of columns defined `className` and `titleClassNames` props that probably got lost during order subscriptions refactoring of `OrderList` component.
These props are actually used in `my-account` app to define the styling of `OrderList` heading columns.
Example:
```JSX
const colClassName = "text-left text-xs font-thin border-b border-gray-200 md:border-none text-gray-300 md:font-semibold md:uppercase md:relative"
const titleClassName = "flex gap-2"
const columns = [
{
header: "Order",
accessorKey: "number",
className: colClassName,
titleClassName,
},
{
header: "Date",
accessorKey: "placed_at",
className: colClassName,
titleClassName,
},
{
header: "Status",
accessorKey: "status",
className: colClassName,
titleClassName,
},
{
header: "Amount",
accessorKey: …
```

Restore `OrderList`'s columns classnames

---

packages/react-components/src/components/orders/OrderList.tsx

I fixed `OrderList` pagination by increasing of 1 the `pageIndex` sent to the API requests. In practice it was sent to the API a `pageNumber` that was always -1 if compared to the clicked page. This misalignment is caused by `react-table` pageIndex starting from 0 instead of 1.

Fix `OrderList` pagination pageIndex

---

packages/react-components/src/components/line_items/LineItemQuantity.tsx
packages/react-components/src/components/line_items/LineItemsContainer.tsx
packages/react-components/src/reducers/LineItemReducer.ts

Closes #
When we have a `line_item` we don't know if has been created with an external price, since `_external_price` is a trigger attribute and nothing is saved at the item level.
What happens now is that when we update a quantity with the `<LineItemQuantity>` component the PATCH request updates the price using the regular price list.
With this PR we are exposing a `hasExternalPrice` prop to `<LineItemQuantity>` so that the consumer app can instruct it to patch the `line_item` using `_external_price: true`.

Allow line_items update using external_price

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressCountrySelector.tsx
packages/react-components/src/components/addresses/AddressStateSelector.tsx
packages/react-components/src/components/customers/CustomerAddressForm.tsx
packages/react-components/src/utils/countryStateCity.ts
packages/react-components/src/utils/isEmptyStates.ts
pnpm-lock.yaml

- Removed `@ac-dev/countries-service` and `@ac-dev/states-service` packages, to use an internal and lighter list of countries with states for `US` and `IT`
- Add the ability to pass a custom list of countries for the `AddressCountrySelector` component
- Add the ability to extend the list of States and provide more options for the `AddressStateSelector` component
Examples
```jsx
// shows only FR, IT, US with localized labels as selectable countries
<AddressCountrySelector
name='billing_address_country_code'
countries={[
{ value: 'ES', label: 'Espana' },
{ value: 'IT', label: 'Italia' },
{ value: 'US', label: 'Unites States of America' }
]}
/>
// shows states as select with predefined options for France
<AddressStateSelector
name='billing_address_state_code'
states={{
FR: [
{ values: 'PA', …
```

Add ability to override Country list or to extends pre-defined list of States 

---

packages/docs/stories/examples/customer/004.subscriptions.mdx
packages/docs/stories/examples/customer/004.subscriptions.stories.tsx

Added a documentation story about `Customer account > Subscription list` in `Examples` section of Storybook.
Following what is shown in `Order list` story of same section here we tell how to create a customer order subscription list using `OrderList` component configured with `type="subscriptions"` prop.

Docs: Add `Subscription list` example story

---

packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/components/orders/OrderList.tsx
packages/react-components/src/reducers/CustomerReducer.ts

- Updated the method to get orders subscriptions orders in `CustomerContainer` component
- Enforced the calculation of the `totalRows` count in `OrderList` component
- Updated the `msw` implementation from v1.x to v2.x according to official [documentation](https://mswjs.io/docs/migrations/1.x-to-2.x/#ctxfetch)
- Renamed from `number` to `id` the `OrderList` and related components prop used to optionally retrieve children resources of a single parent resource

fix: Improve the retrieval of orders of an order subscription

---

packages/react-components/src/components/orders/OrderList.tsx

Enforced the `OrderList` component data calculation to manage all the usages of component props that are influencing the content of its rows.

Enforce `OrderList` data for subscription orders

---

packages/react-components/src/components/orders/OrderList.tsx

Fixed conditional in `OrderList` data calculation of `subscriptions`

Fix: fix conditional in `OrderList` data calculation

---

packages/docs/stories/examples/customer/002.address-form.mdx

I've fixed a small typo in documentation replacing `values` with `value`

Fx typo in states documentation

---

lerna.json
packages/docs/stories/examples/checkout/002.addresses.stories.tsx
packages/react-components/package.json
packages/react-components/specs/in_stock_subscriptions/in_stock_subscriptions.spec.tsx
packages/react-components/src/components/addresses/AddressInput.tsx
packages/react-components/src/components/addresses/BillingAddressForm.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/components/errors/Errors.tsx
packages/react-components/src/components/utils/BaseInput.tsx
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/reducers/PlaceOrderReducer.ts
packages/react-components/src/utils/hasSubscriptions.ts
packages/react-components/src/utils/updateOrderSubscriptionCustomerPaymentSource.ts

Modified the `PlaceOrderReducer` introducing a new procedure to update the customer payment source of current order's subscription.
Once the order is placed by the reducer's flow, and it is confirmed that it has subscriptions, the new procedure will take care about:
- retrieving current order including `payment_source`, `order_subscription` and `order_subscription.customer_payment_source`
- checking if retrieved `payment_source` exists
- updating `order_subscription.customer_payment_source` setting its relationship to point to order's `payment_source`
If you have an `order_subscription` with status `active` and an empty or expired / not working `customer_payment_source` you can try to checkout subscription most recent order with `Unpaid` status and place the order with an updated / valid …

Update customer payment source of a subscription after order place

---

lerna.json
packages/docs/stories/examples/cart/001.cart.mdx
packages/docs/stories/examples/cart/001.cart.stories.tsx
packages/react-components/package.json
packages/react-components/src/components/addresses/BillingAddressForm.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponCode.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponForm.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponInput.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponRemoveButton.tsx
packages/react-components/src/reducers/OrderReducer.ts

- **fix: Set code type on Gift card or coupon components**
- **feat: Add new prop `fieldEvent` to Billing and Shipping address components**

Add `codeType` to gift card or coupon code components

---

lerna.json
packages/docs/stories/examples/cart/001.cart.mdx
packages/docs/stories/examples/cart/001.cart.stories.tsx
packages/react-components/package.json
packages/react-components/src/components/addresses/BillingAddressForm.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponCode.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponForm.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponInput.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponRemoveButton.tsx
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/reducers/OrderReducer.ts

Add new prop `loadingLabel` to `<PlaceOrderButton />` in order to allow the developer to change the loading status label when the user places the order.
On the documentation

Add new prop `loadingLabel` to `PlaceOrderButton` component.

---

packages/react-components/src/components/orders/HostedCart.tsx

On mini-cart, during the first loading, the iframe event could be not fully synched with the loading of the cart URL, so side padding sometimes is not applied.
A safer solution is to have the same padding left and right applied directly to the iframe tag, without relying on iframe events.

Move side padding from mini cart body to iframe

---

packages/react-components/src/components/payment_gateways/PaypalGateway.tsx
packages/react-components/src/components/payment_gateways/WireTransferGateway.tsx

- **Avoid double click on selecting a shipping method.**
- **Avoid show card for wiretransfer and paypal payment methods.**

Avoid show card for wiretransfer and paypal payment methods.

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/customers/MyAccountLink.tsx
packages/react-components/src/components/orders/CheckoutLink.tsx

Checkout link provided by organization config

---

packages/react-components/src/components/payment_source/CheckoutComPayment.tsx

Fix CKO config types

---

packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/components/orders/OrderList.tsx
packages/react-components/src/reducers/CustomerReducer.ts

Following the previous PR related to enabling server side ordering to the `OrderList` component we now gave support for the server side ordering when the component is used for showing `order subscriptions` and orders related to an order subscription.

Enable server side sorting for order subscriptions

---

packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/reducers/CustomerReducer.ts

- Avoided the retrieval of orders and orders subscription during `CustomerContainer` setup to avoid unused requests
- Enhanced wallet page by setting default sort to `updated_at` `DESC` to see more recent customer payment sources first

Enhance customer resources requests
