commercelayer/commercelayer-react-components

pages/checkout-customer-payments.tsx
pages/checkout-payments.tsx
src/components/BillingAddressContainer.tsx
src/components/CustomerContainer.tsx
src/components/PaymentMethod.tsx
src/components/ShipmentField.tsx
src/components/ShippingAddressContainer.tsx

- feat: Add activeClassName prop
- feat: Convert to `span` instead of `p`
- fix: React useEffect warnings

Feat: Enhancements

---

pages/order-with-sku-options.tsx
src/components/LineItemOption.tsx
src/components/LineItemOptions.tsx
src/components/PaymentGateway.tsx
src/components/PaymentMethod.tsx
src/components/PaymentSource.tsx
src/components/Shipment.tsx
src/config/components.ts
src/typings/index.ts
src/utils/getLoaderComponent.tsx
src/utils/isJSON.ts

- feat: Convert to HTML list
- feat: Add Loader to shipments and payments

feat: Add loader to shipments and payments

---

pages/checkout-addresses.tsx
pages/checkout-customer-addresses.tsx
pages/checkout-customer-payments.tsx
pages/checkout-payments.tsx
src/components/Address.tsx
src/components/AddressInput.tsx
src/components/BillingAddressForm.tsx
src/components/PaymentMethodsContainer.tsx
src/components/PaypalPayment.tsx
src/components/PlaceOrderButton.tsx
src/components/StripePayment.tsx
src/components/WireTransferPayment.tsx
src/config/components.ts
src/context/BillingAddressFormContext.ts
src/context/PaymentMethodContext.ts
src/reducers/AddressReducer.ts
src/reducers/PaymentMethodReducer.ts
src/reducers/PlaceOrderReducer.ts
src/typings/index.ts

- feat: Add billing_info field
- feat: Place order without set payment button
- chore: Update examples
- chore: Remove unused code

feat: Add place order without set payment button

---

pages/checkout-customer-payments.tsx
src/components/BraintreePayment.tsx
src/components/PaymentGateway.tsx
src/components/StripePayment.tsx
src/reducers/OrderReducer.ts
src/reducers/PlaceOrderReducer.ts
src/utils/customerOrderOptions.ts
src/utils/localStorage.ts
src/utils/promisify.ts

- feat: Add 3D Secure for Braintree
- feat: Add new function promisify
- fix: Update order properly
- feat: Add promise flow with Braintree
- chore: Clean code
- feat: Save wallet before placing the order
- fix: Save customer address flag in local storage.

feat: Add braintree gateway

---

src/reducers/CustomerReducer.ts
src/reducers/GiftCardReducer.ts
src/reducers/LineItemReducer.ts
src/reducers/OrderReducer.ts
src/reducers/PaymentMethodReducer.ts
src/reducers/PlaceOrderReducer.ts
src/reducers/SkuListsReducer.ts
src/utils/customerOrderOptions.ts

- fix: Add a trigger attribute per request
- fix: Set types
- fix: Remove unused code

Fix: Remove multi trgger attributes in a single request

---

package-lock.json
package.json
src/utils/countryStateCity.ts
src/utils/isEmptyStates.ts

- feat: Filter states by US, GB and IT
- chore: Remove unused code
- feat: Add countries-states-cities-service

feat: Enable states only for IT and US

---

src/components/AddressStateSelector.tsx
src/components/BillingAddressForm.tsx
src/components/SaveAddressesButton.tsx
src/components/ShippingAddressForm.tsx
src/reducers/AddressReducer.ts
src/utils/validateFormFields.ts

- feat: Add selectClassName and className turns into a default class
- fix: Multple errors for the same field

Feat: New props selectClassName

---

package-lock.json
package.json
pages/checkout-customer-payments.tsx
pages/checkout-payments.tsx
src/components/AdyenPayment.tsx
src/components/CustomerContainer.tsx
src/components/PaymentGateway.tsx
src/components/PaymentMethodsContainer.tsx
src/components/PaymentSource.tsx
src/components/PaymentSourceDetail.tsx
src/components/PlaceOrderButton.tsx
src/components/StripePayment.tsx
src/components/gateways/AdyenGateway.tsx
src/components/gateways/BraintreeGateway.tsx
src/components/gateways/PaypalGateway.tsx
src/components/gateways/StripeGateway.tsx
src/components/gateways/WireTransferGateway.tsx
src/config/components.ts
src/context/CustomerContext.ts
src/context/PaymentMethodContext.ts
src/reducers/CustomerReducer.ts
src/reducers/PaymentMethodReducer.ts
src/utils/browserInfo.ts

- feat: Split and improve code
- feat: Set and show Adyen card form
- feat: Split payment gateways and add Adyen gateway
- feat: Add payment by wallet card
- feat: Read adyen environment by api mode

feat: Add Adyen gateway

---

src/components/BillingAddressForm.tsx
src/components/CustomerContainer.tsx
src/components/LineItemsContainer.tsx
src/components/OrderContainer.tsx
src/components/PaymentMethodsContainer.tsx
src/components/PlaceOrderContainer.tsx
src/components/ShipmentsContainer.tsx
src/components/ShippingAddressForm.tsx
src/components/gateways/AdyenGateway.tsx
src/reducers/AddressReducer.ts
src/reducers/OrderReducer.ts
src/utils/localStorage.ts

- fix: Save customer address book and include order resources
- fix: Manage resources to include

fix: Include order resources

---

pages/order-summary.tsx
src/components/AdyenPayment.tsx
src/components/OrderContainer.tsx
src/components/Price.tsx

- fix: Add RedirectShopper
- fix: Clean order when it is placed
- fix: Expose prices resource within Price custom children props
- chore: Remove OrderStorage

fix: Clean order when it is placed

---

pages/checkout/customer/addresses.tsx
pages/checkout/customer/index.tsx
src/components/BillingAddressForm.tsx
src/components/GiftCardOrCouponCode.tsx
src/components/PricesContainer.tsx
src/components/ShippingAddressForm.tsx
src/config/components.ts

- fix: Hydrate props properly
- fix: Duplicate customer addresses
- chore: Update demo pages

fix: Duplicate customer addresses

---

src/components/GiftCardOrCouponRemoveButton.tsx
src/reducers/PlaceOrderReducer.ts
src/utils/addressesManager.ts

- fix: Address country lock controller
- fix: Show GiftCardOrCouponRemoveButton properly
- fix: Place an order with total amount equal to zero

fix: Place order with total amount equal to zero

---

package-lock.json
package.json
pages/checkout/customer/index.tsx
pages/checkout/customer/payments.tsx
src/components/PaymentSourceDetail.tsx
src/components/PaypalPayment.tsx
src/components/VariantsContainer.tsx
src/config/components.ts
src/context/PaymentSourceContext.ts
src/reducers/PaymentMethodReducer.ts

- fix: Remove useMemo
- chore: Update demo pages
- fix: Show card details and paypal gateway
- chore: Update @commercelayer/sdk

fix: payment source components

---

.gitignore
pages/checkout/customer/payments.tsx
src/components/PlaceOrderButton.tsx
src/components/Price.tsx
src/reducers/PlaceOrderReducer.ts
src/reducers/VariantReducer.ts

- fix: Place order by paypal
- chore: Update .gitignore

fix: Place order by paypal

---

pages/checkout/customer/index.tsx
src/components/PlaceOrderButton.tsx
src/reducers/PaymentMethodReducer.ts
src/reducers/PlaceOrderReducer.ts
src/utils/getErrors.ts
src/utils/getPrices.tsx

- fix: Cannot read property 'map'

fix: Cannot read property map

---

src/components/AdjustmentAmount.tsx
src/components/LineItemsCount.tsx
src/components/LineItemsEmpty.tsx
src/components/PricesContainer.tsx
src/config/components.ts
src/utils/getLineItemsCount.ts

- fix: Reload Price component
- feat: Add new component AdjustmentAmount
- feat: Add new prop typeAccepted to LineItemsCount

feat: Add AdjustmentAmount component

---

pages/checkout/addresses.tsx
src/index.ts

- chore: export types for address form and errors
- fix: import getSdk in example page

feat: Expose address form and error types

---

.eslintignore
.eslintrc.js
package.json
pages/checkout/giftcard-or-coupon-code.tsx
src/components/Address.tsx
src/components/AddressInput.tsx
src/components/AddressesContainer.tsx
src/components/AdyenPayment.tsx
src/components/BillingAddressForm.tsx
src/components/SaveAddressesButton.tsx
src/components/ShippingAddressForm.tsx
src/components/utils/AddressCardsTemplate.tsx
src/context/CustomerContext.ts
src/typings/index.ts
src/utils/addressesManager.ts
src/utils/validateFormFields.ts

- feat: Expose address as param of onSelect function
- chore: Update ESlint config
- fix: Reset form properly when isBusiness changes

fix: Address form

---

README.md

This PR updates external links to the documentation that has changed.

Update changed links

---

.babelrc.js
.eslintrc.js
babel.config.js
nyc.config.js
package-lock.json
package.json
pages/checkout/addresses.tsx
playwright.config.ts
specs/e2e/baseFixtures.ts
specs/e2e/checkout/customer/addresses-country-lock.spec.ts
src/components/BillingAddressForm.tsx
src/utils/PropsType.ts
src/utils/validateFormFields.ts

- fix: Save line_2 value properly
- chore: Add coverage to playwrite suite

fix: Save line_2 value

---

config.env.test
next.config.js
pages/checkout/shipments.tsx
src/components/PaypalPayment.tsx
src/components/gateways/AdyenGateway.tsx
src/components/gateways/BraintreeGateway.tsx
src/components/gateways/CheckoutComGateway.tsx
src/components/gateways/PaypalGateway.tsx
src/components/gateways/StripeGateway.tsx
src/typings/errors.ts

- chore: Remove unused config
- fix: Show selected customer card

fix: Show selected customer card

---

package-lock.json
package.json
src/components/LineItemsContainer.tsx
src/components/OrderContainer.tsx
src/components/ShipmentsContainer.tsx
src/reducers/OrderReducer.ts
src/reducers/PlaceOrderReducer.ts
src/utils/shipments.ts

- fix: Reload the order  when a coupon is added or removed
- fix: Set @commercelayer/js-auth to latest version `2.3.0`
- fix: Check if there is `do_not_ship` set `true` and the order doesn't have the shipping address

fix: Coupon and check `do_not_ship` attribute

---

pages/checkout/giftcard-or-coupon-code.tsx
src/components/GiftCardOrCouponForm.tsx
src/components/OrderContainer.tsx
src/components/utils/getAllErrors.tsx
src/context/OrderContext.ts
src/reducers/OrderReducer.ts
src/reducers/PlaceOrderReducer.ts

- perf: Clean message if title and detail are equal
- fix: Callback response from `Errors` component

fix: Callback response from `Errors` component

---

pages/cart.tsx
src/components/Errors.tsx
src/components/PaymentGateway.tsx
src/components/PaymentMethodRadioButton.tsx
src/components/PlaceOrderButton.tsx
src/components/ShippingMethodPrice.tsx
src/components/utils/getAllErrors.tsx

- fix: Duplicate error messages
- fix: Duplicate `payment_source` request
- fix: Children props types
- fix: Children props types
- perf: Use `labelFreeOver` when the amount is equal to zero

fix: Create payment source

---

pages/cart.tsx
src/components/OrderContainer.tsx
src/components/SkuField.tsx
src/components/StockTransferField.tsx
src/components/utils/BaseOrderPrice.tsx
src/reducers/OrderReducer.ts
src/utils/checkIncludeResource.ts

- fix: The `StockTransferField` reads HTML attribute properly

fix: `StockTransferField` component

---

.eslintignore
package.json
pages/checkout/giftcard-or-coupon-code.tsx
src/components/GiftCardOrCouponCode.tsx
src/components/GiftCardOrCouponSubmit.tsx
src/components/LineItemImage.tsx
src/components/utils/BaseInput.tsx
src/components/utils/GenericFieldComponent.tsx
src/components/utils/Parent.tsx
src/typings/index.ts
src/utils/placeholderImages.ts

- chore: Remove pages folder from eslint and mimize d.ts files

fix: Stock transfer placeholder image

---

src/components/Shipment.tsx

- perf: Add await before dispatching the callback event

perf: Auto select shipping method

---

src/components/Shipment.tsx
src/components/ShippingMethodPrice.tsx

- fix: Shipping method price label
- fix: Remove glitch on auto-preselecting the shipping method

fix: Shipping method

---

src/components/OrderContainer.tsx
src/components/QuantitySelector.tsx
src/utils/compareObjAttribute.ts

- fix: Set default value to `QuantitySelector`
- perf: Avoid duplicate requests from external re-rendering

fix: Default value on `QuantitySelector` component

---

src/components/QuantitySelector.tsx

fix: Set default value to `QuantitySelectory` componennt

---

src/components/AvailabilityContainer.tsx

fix: Avoid availability container infinite loop

---

package.json
src/components/PaymentMethod.tsx
src/components/Shipment.tsx
src/utils/validateFormFields.ts

- fix: Loading autoselect payment method
- fix: Remove `line_2` field as required for business address

fix: Loading preselect payment method

---

packages/react-components/mocks/handlers.ts
packages/react-components/package.json
packages/react-components/specs/orders/order-container.spec.tsx
packages/react-components/src/components/orders/OrderContainer.tsx
packages/react-components/src/components/orders/OrderListPaginationButtons.tsx
packages/react-components/src/components/orders/OrderListPaginationInfo.tsx
packages/react-components/src/components/payment_methods/PaymentMethodsContainer.tsx
packages/react-components/src/reducers/OrderReducer.ts
packages/react-components/src/utils/hooks/useCustomContext.ts
pnpm-lock.yaml

fix: Include propagation on re-rendering

---

packages/docs/.storybook/main.ts

fix: Docs build error

---

packages/react-components/src/components/orders/OrderContainer.tsx

fix: Dispatch `fetchOrder` callback using `useMemo`

---

packages/react-components/src/components/addresses/AddressesContainer.tsx
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/components/orders/OrderContainer.tsx
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/context/AddressContext.ts
packages/react-components/src/context/PlaceOrderContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/reducers/OrderReducer.ts
packages/react-components/src/reducers/PlaceOrderReducer.ts

perf: Expose order resource into callback function

---

packages/react-components/src/components/gift_cards/GiftCardOrCouponForm.tsx
packages/react-components/src/components/gift_cards/GiftCardOrCouponRemoveButton.tsx
packages/react-components/src/components/payment_methods/PaymentMethod.tsx
packages/react-components/src/components/payment_methods/PaymentMethodRadioButton.tsx
packages/react-components/src/components/shipments/Shipment.tsx
packages/react-components/src/components/shipping_methods/ShippingMethodRadioButton.tsx
packages/react-components/src/components/utils/PaymentCardsTemplate.tsx
packages/react-components/src/context/OrderContext.ts
packages/react-components/src/context/PaymentMethodContext.ts
packages/react-components/src/context/ShipmentContext.ts
packages/react-components/src/index.ts
packages/react-components/src/reducers/OrderReducer.ts
packages/react-components/src/reducers/PaymentMethodReducer.ts
packages/react-components/src/reducers/ShipmentReducer.ts

perf: Get order from callback and refactor code

---

packages/react-components/src/components/orders/OrderContainer.tsx
packages/react-components/src/components/payment_methods/PaymentMethod.tsx
packages/react-components/src/components/payment_source/WireTransferPayment.tsx
packages/react-components/src/components/shipments/Shipment.tsx
packages/react-components/src/reducers/PaymentMethodReducer.ts

perf: Expose order resource as param into `autoSelectShippingMethod` callback

---

packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/payment_source/AdyenPayment.tsx
packages/react-components/src/components/payment_source/PaymentSourceBrandName.tsx

fix: Auto place order using Paypal or Klarna throught Adyen payment

---

packages/react-components/mocks/handlers.ts
packages/react-components/specs/parcels/parcels.spec.tsx
packages/react-components/src/components/shipments/Shipment.tsx
packages/react-components/src/components/shipments/ShipmentsContainer.tsx

fix: Perpetual loading on parcels components

---

packages/react-components/specs/orders/order-list.spec.tsx
packages/react-components/src/components/orders/OrderList.tsx
packages/react-components/src/components/shipments/Shipment.tsx

Resolve https://github.com/commercelayer/commercelayer-react-components/issues/332

fix: Order list props hydratation

---

packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/utils/localStorage.ts

fix: Customer adyen payments

---

packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/reducers/CustomerReducer.ts

fix: Delete/edit customer address

---

packages/react-components/src/components/orders/CheckoutLink.tsx

fix: New checkout link

---

packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/reducers/CustomerReducer.ts

fix: Show customer addresses on hosted checkout

---

packages/react-components/src/components/line_items/LineItemOptions.tsx
packages/react-components/src/context/LineItemOptionChildrenContext.ts

fix: Types

---

lerna.json
packages/react-components/package.json
packages/react-components/tsconfig.prod.esm.json
packages/react-components/tsconfig.prod.json

v4.4.0-beta.3

---

packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
packages/react-components/src/utils/expressPaymentHelper.ts

fix: Set customer email into the order before dispatching the `confirmCardPayment` method.

---

packages/react-components/src/utils/expressPaymentHelper.ts

fix: Comment the update of payment_source before placing the order.

---

packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
packages/react-components/src/utils/expressPaymentHelper.ts

fix: Update order total before placing the order

---

packages/react-components/src/components/orders/CheckoutLink.tsx
packages/react-components/src/utils/expressPaymentHelper.ts
packages/react-components/src/utils/getCartLink.ts

fix: Add `https://` to all links

---

packages/react-components/mocks/getAccessToken.ts
packages/react-components/specs/orders/add-to-cart-button.spec.tsx
packages/react-components/src/components/orders/AddToCartButton.tsx
packages/react-components/src/components/orders/CartLink.tsx
packages/react-components/src/utils/expressPaymentHelper.ts
packages/react-components/src/utils/getCartLink.ts
packages/react-components/src/utils/getDomain.ts

fix: `<CartLink/>` href has built from endpoint instead of the node environment

---

packages/react-components/src/components/orders/OrderContainer.tsx

fix: Reload order if the persist key change

---

packages/react-components/specs/hooks/useCommerceLayer.spec.tsx
packages/react-components/src/hooks/useCommerceLayer.ts

feat: Add new hooks `useCommerceLayer`

---

packages/react-components/src/reducers/PlaceOrderReducer.ts

fix: Remove `_create_subscription` after placing the order.

---

packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/components/payment_gateways/StripeGateway.tsx
packages/react-components/src/components/payment_source/PaymentSource.tsx
packages/react-components/src/reducers/OrderReducer.ts
packages/react-components/src/reducers/PlaceOrderReducer.ts
packages/react-components/src/utils/getCardDetails.ts

fix: Use customer payment source to place an order

---

packages/react-components/specs/customers/customer-payments.spec.tsx
packages/react-components/specs/line_items/line-items.spec.tsx
packages/react-components/specs/parcels/parcels.spec.tsx
packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/components/customers/MyIdentityLink.tsx
packages/react-components/src/components/orders/HostedCart.tsx
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/payment_source/PaymentSource.tsx
packages/react-components/src/components/payment_source/PaymentSourceBrandIcon.tsx
packages/react-components/src/components/payment_source/PaymentSourceDetail.tsx
packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
packages/react-components/src/components/shipping_methods/ShippingMethodPrice.tsx
packages/react-components/src/context/CustomerPaymentSourceContext.ts
packages/react-components/src/context/PaymentSourceContext.ts
packages/react-components/src/reducers/PaymentMethodReducer.ts
packages/react-components/src/typings/index.ts
packages/react-components/src/utils/getCardDetails.ts
packages/react-components/src/utils/validateFormFields.ts

fix: Show payments brand with new stripe integration

---

packages/react-components/src/components/orders/HostedCart.tsx
packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/components/payment_source/StripePayment.tsx
packages/react-components/src/reducers/PlaceOrderReducer.ts
packages/react-components/src/utils/getPaymentAttributes.ts

fix: Remove `return_url` and add `off_session` atttribute on stripe payments resource

---

.gitignore
.vscode/settings.json
packages/react-components/src/components/customers/MyAccountLink.tsx
packages/react-components/src/components/customers/MyIdentityLink.tsx
packages/react-components/src/components/orders/HostedCart.tsx

- Fix `accessToken` when it is an empty string to generate the hosted cart link.
- Merge custom styles with default ones.
- Fix types for MFE components.
- Add `.vscode` folder public.
`pnpm t`

fix: Merge custom styles and types

---

packages/react-components/src/components/orders/HostedCart.tsx

chore: Lint fix

---

packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/reducers/PlaceOrderReducer.ts
packages/react-components/src/utils/getPaymentAttributes.ts

fix: Restore `return_url` for stripe payments resource.

---

packages/react-components/src/components/shipments/Shipment.tsx
packages/react-components/src/components/shipments/ShipmentsContainer.tsx
packages/react-components/src/components/shipping_methods/ShippingMethod.tsx
packages/react-components/src/components/shipping_methods/ShippingMethodRadioButton.tsx
packages/react-components/src/context/ShipmentChildrenContext.ts

fix: Select shipping methods.

---

packages/react-components/specs/hooks/useCustomerContainer.spec.tsx
packages/react-components/src/context/OrderContext.ts
packages/react-components/src/hooks/useCustomerContainer.ts
packages/react-components/src/hooks/useOrderContainer.ts
packages/react-components/src/reducers/OrderReducer.ts

feat: Add new hook `useCustomerContainer`, expose `createOrder` and `addToCart` on `useOrderContainer`

---

packages/docs/package.json

chore: Remove build script for docs package

---

lerna.json

chore: Fix lerna configuration.

---

packages/react-components/src/utils/getCardDetails.ts

fix: Show klarna icon.

---

packages/react-components/src/context/BillingAddressFormContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/reducers/CustomerReducer.ts
packages/react-components/src/typings/index.ts

feat: Add metadata to billing and shipping address by `AddressInput` component

---

packages/react-components/src/components/line_items/LineItemQuantity.tsx
packages/react-components/src/components/line_items/LineItemRemoveLink.tsx
packages/react-components/src/utils/getApplicationLink.ts

fix: customDomain for self hosted application

---

packages/react-components/specs/addresses/invert-addresses.spec.tsx
packages/react-components/src/components/addresses/AddressInput.tsx
packages/react-components/src/components/addresses/AddressesContainer.tsx
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/context/BillingAddressFormContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/typings/index.ts
packages/react-components/src/utils/addressesManager.ts

feat: Add `invertAddresses` prop to `<AddressesContainer/>`

---

packages/react-components/src/components/shipping_methods/ShippingMethodRadioButton.tsx

Avoid `ShippingMethodRadioButton` to lose focus when selected

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/OrderListRow.tsx
packages/react-components/src/components/shipping_methods/ShippingMethodRadioButton.tsx

Fix `ShippingMethodRadioButton` losing focus and fix order list nested `td`

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/utils/addressesManager.ts

fix: Country code lock with digital SKUs.

---

packages/react-components/src/utils/addressesManager.ts

fix: Filters line items by type on country lock

---

packages/react-components/src/components/orders/HostedCart.tsx
packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/components/payment_source/PaymentSource.tsx

fix: Show payments methods not compatible with express payment on the cart.

---

packages/react-components/src/components/line_items/LineItemsCount.tsx

chore: Remove console.log

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/customers/CustomerInput.tsx
packages/react-components/src/components/payment_source/ExternalPayment.tsx
packages/react-components/src/utils/validateFormFields.ts
pnpm-lock.yaml

fix: Expose props to custom component function

---

packages/react-components/src/components/customers/CustomerInput.tsx
packages/react-components/src/utils/validateFormFields.ts

fix: Customer email validation.

---

packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/components/customers/CustomerInput.tsx

fix: Add customer email validation into `SaveAddressesButton`.

---

lerna.json
packages/react-components/package.json
packages/react-components/specs/addresses/invert-addresses.spec.tsx
packages/react-components/src/components/addresses/AddressesContainer.tsx
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/context/BillingAddressFormContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/typings/index.ts
packages/react-components/src/utils/addressesManager.ts

Add support for inverting shipping and billing addresses

---

.vscode/settings.json
lerna.json
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressInput.tsx
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/components/customers/CustomerContainer.tsx
packages/react-components/src/components/orders/AddToCartButton.tsx
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/payment_gateways/AdyenGateway.tsx
packages/react-components/src/components/payment_source/PaymentSource.tsx
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/reducers/OrderReducer.ts
packages/react-components/src/reducers/PaymentMethodReducer.ts
packages/react-components/src/reducers/PlaceOrderReducer.ts
packages/react-components/src/utils/addressesManager.ts

fix: Use Customer cards imported by API

---

packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/utils/addressesManager.ts

fix: Invert addresses flow when there is the billing info required.

---

packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/payment_source/KlarnaPayment.tsx
packages/react-components/src/components/payment_source/PaymentSource.tsx

fix: Import customer payment sources flow.

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/stock_transfers/StockTransferField.tsx
packages/react-components/src/components/utils/GenericFieldComponent.tsx
packages/react-components/src/reducers/PlaceOrderReducer.ts

fix: Adyen payents flow and show stock transfers.

---

packages/docs/.storybook/preview.tsx
packages/docs/stories/cart/AddToCartButton.stories.tsx
packages/docs/stories/hooks/001.useCommerceLayer.mdx
packages/docs/stories/hooks/002.useOrderContainer.mdx
packages/docs/stories/hooks/003.useCustomerContainer.mdx
packages/react-components/src/hooks/useCommerceLayer.ts
packages/react-components/src/hooks/useCustomerContainer.ts
packages/react-components/src/hooks/useOrderContainer.ts

I've added documentation (in storybook) for the following hooks:
- useCommerceLayer
- useOrderContainer
- useCustomerContainer 
1. Checkout the branch `docs/hooks`
2. Run `pnpm docs:dev`
3. Open `http://localhost:6006/?path=/docs/hooks-usecommercelayer--docs`

Add documentation for exported hooks

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/orders/PlaceOrderContainer.tsx
packages/react-components/src/components/payment_source/AdyenPayment.tsx
packages/react-components/src/reducers/PlaceOrderReducer.ts
pnpm-lock.yaml

fix: Adyen payments input flow.

---

.github/workflows/gh-pages.yaml

I've enabled the building of documentation for every update received from the `main` branch

Update workflow to trigger storybook build from main branch

---

packages/docs/stories/examples/checkout/002.addresses.mdx
packages/docs/stories/examples/checkout/002.addresses.stories.tsx

feat: Add invert addresses documentation.

---

packages/react-components/README.md

feat: Update README.

---

lerna.json
package.json
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressStateSelector.tsx
packages/react-components/src/components/addresses/AddressesContainer.tsx
packages/react-components/src/components/addresses/BillingAddressForm.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/context/AddressContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/utils/formCleaner.ts

fix: Set value on address inputs.

---

packages/react-components/src/components/utils/getAllErrors.tsx

fix: Avoid empty string in error messages

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/orders/PlaceOrderContainer.tsx
packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/components/payment_methods/PaymentMethod.tsx
packages/react-components/src/components/payment_methods/PaymentMethodRadioButton.tsx
packages/react-components/src/context/PlaceOrderContext.ts
packages/react-components/src/reducers/PlaceOrderReducer.ts

Disable select payment methods when placing an order.

---

lerna.json
packages/docs/stories/examples/checkout/002.addresses.stories.tsx
packages/react-components/package.json
packages/react-components/src/components/orders/PlaceOrderButton.tsx
packages/react-components/src/components/payment_gateways/AdyenGateway.tsx
packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
packages/react-components/src/components/payment_source/AdyenPayment.tsx

docs: Update addresses example

---

packages/react-components/src/reducers/OrderReducer.ts

Add `_update_quantity` to addToCart function

---

packages/react-components/src/components/addresses/AddressStateSelector.tsx
packages/react-components/src/utils/validateFormFields.ts

Set `AddressStateSelector` not required.

---

packages/docs/stories/examples/checkout/000.intro.mdx
packages/docs/stories/examples/customer/000.intro.mdx
packages/docs/stories/getting-started/001.introduction.mdx

Correct a typo Introdution -> Introduction

Fix typo in documentation

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/payment_source/AdyenPayment.tsx

Allows the shopper to remove a stored payment method.

---

lerna.json
packages/docs/stories/examples/checkout/002.addresses.stories.tsx
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressStateSelector.tsx
packages/react-components/src/components/addresses/BillingAddressForm.tsx
packages/react-components/src/components/addresses/ShippingAddressForm.tsx
packages/react-components/src/reducers/AddressReducer.ts

It is possible to validate multi-fields using `customFieldMessageError` when a single value changes.
Just return an array with objects as you can see in the following example:
```tsx
<BillingAddressForm
customFieldMessageError={(props) => {
const regex = /[a-zA-Z]+/g
const phoneRegex = /^\d+$/
const textWithSpace = /^[a-zA-Z0-9\s]{1,20}$/
console.log('props.value billing', props.value)
if (
props.field === 'billing_address_first_name' &&
!regex.test(props.value)
) {
return 'Validation error - only characters are allowed - this is a custom message'
}
if (props.field === 'billing_address_metadata_phone') {
return props.value === ''
? null
: !phoneRegex.test(props.value)
? 'Validation error - only numbers are allowed - this is a custom message'
: null
}
if (
props.field === …
```

Add multi fields validation

---

packages/react-components/src/reducers/CustomerReducer.ts

Fix missing customer address reference

---

packages/react-components/src/components/payment_source/AdyenPayment.tsx

Set adyen shopper ip

---

packages/react-components/src/components/payment_source/AdyenPayment.tsx

Set right attribute for shopper ip

---

packages/react-components/src/components/orders/CheckoutLink.tsx
packages/react-components/src/reducers/OrderReducer.ts

Change checkout url using the buy now mode

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressStateSelector.tsx
packages/react-components/src/components/orders/CheckoutLink.tsx
packages/react-components/src/components/utils/BaseSelect.tsx

Address fields

---

lerna.json
package.json
packages/react-components/package.json
packages/react-components/src/components/addresses/AddressesContainer.tsx
packages/react-components/src/components/addresses/SaveAddressesButton.tsx
packages/react-components/src/context/AddressContext.ts
packages/react-components/src/reducers/AddressReducer.ts
packages/react-components/src/reducers/CustomerReducer.ts
packages/react-components/src/utils/addressesManager.ts
pnpm-lock.yaml

Update Order: Set customer address using the `invertAddresses` prop

---

lerna.json
packages/react-components/README.md
packages/react-components/package.json
packages/react-components/src/components/payment_source/AdyenPayment.tsx
packages/react-components/src/components/payment_source/BraintreePayment.tsx

This PR addresses a bug related to Apple Pay payment processing on Stripe, and Adyen. The issue was causing payment failures under specific conditions, preventing users from completing transactions successfully.

Apple Pay Payment Processing Issue

---

lerna.json
packages/react-components/README.md
packages/react-components/package.json
packages/react-components/src/components/payment_source/AdyenPayment.tsx
packages/react-components/src/components/payment_source/BraintreePayment.tsx

This pull request enforces a 3DS (3D Secure) challenge request in the Braintree payment integration to enhance transaction security. By mandating a 3DS challenge, this change aims to reduce fraud risk and ensure compliance with strong customer authentication (SCA) requirements.

Enforce 3DS Challenge Request in Braintree Payment Integration

---

packages/react-components/package.json
packages/react-components/src/components/customers/MyAccountLink.tsx
packages/react-components/src/components/customers/MyIdentityLink.tsx
packages/react-components/src/components/orders/AddToCartButton.tsx
packages/react-components/src/components/orders/CartLink.tsx
packages/react-components/src/components/orders/CheckoutLink.tsx
packages/react-components/src/components/orders/HostedCart.tsx
packages/react-components/src/reducers/OrderReducer.ts
pnpm-lock.yaml

I added the `slug` param to the organization config so that `:slug` can be used in the url.

Send `:slug` for replacement to the organization.config

---

lerna.json
packages/react-components/package.json
packages/react-components/src/components/payment_gateways/AdyenGateway.tsx
packages/react-components/src/components/payment_source/AdyenPayment.tsx
packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
pnpm-lock.yaml

- **Add Adyen subscriptions**
- **Hide customer payments when the order contains a subscription**

Hide and filter available payments when the order contains a subscription
